language: go
go:
  - 1.2.x

install:
  - go get -v ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r -v
